/**
 *Jet Manager- Integrantes:
 * @author JOSÉ PIRELA
 * @author ANA DE PALMA
 * @author JULIO PAREDES
 * @author RICARDO ABUNASSAR
 * @author JESÚS RANGEL
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ABUNASSAR PENARANDA
 */
public class VPagoDeNomina extends javax.swing.JFrame {

    /**
     * Creates new form VPagoDeNomina
     */
    public VPagoDeNomina() {
        initComponents();
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public JComboBox<String> getCmbEmpleadoPagar1() {
        return cmbEmpleadoPagar1;
    }

    public JComboBox<String> getCmbMesPagar() {
        return cmbMesPagar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JPanel getJpanEncabezado1() {
        return jpanEncabezado1;
    }

    public JLabel getLblRegistrarCandidato1() {
        return lblRegistrarCandidato1;
    }

    public JPanel getPanPago() {
        return panPago;
    }

    public JTextField getTxtMontoPagar() {
        return txtMontoPagar;
    }

    public JButton getBtnCalcular() {
        return btnCalcular;
    }

    public JButton getBtnRealizar1() {
        return btnRealizar1;
    }
     
    public void Agregar_Listener(ActionListener ac)
   {
   
       this.btnCancelar.addActionListener(ac);
       this.btnCalcular.addActionListener(ac);
       this.btnSalir.addActionListener(ac);
       this.btnRealizar1.addActionListener(ac);
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanEncabezado1 = new javax.swing.JPanel();
        lblRegistrarCandidato1 = new javax.swing.JLabel();
        panPago = new javax.swing.JPanel();
        cmbMesPagar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbEmpleadoPagar1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMontoPagar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRealizar1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanEncabezado1.setBackground(new java.awt.Color(255, 153, 51));
        jpanEncabezado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistrarCandidato1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        lblRegistrarCandidato1.setText("PAGO A EMPLEADOS");
        jpanEncabezado1.add(lblRegistrarCandidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 22, -1, -1));

        getContentPane().add(jpanEncabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 80));

        panPago.setBackground(new java.awt.Color(102, 102, 102));
        panPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMesPagar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbMesPagar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        panPago.add(cmbMesPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 200, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Monto a pagar:");
        panPago.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Empleado a pagar:");
        panPago.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        cmbEmpleadoPagar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbEmpleadoPagar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        panPago.add(cmbEmpleadoPagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mes a pagar:");
        panPago.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        txtMontoPagar.setEditable(false);
        txtMontoPagar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        panPago.add(txtMontoPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, -1));

        btnSalir.setBackground(new java.awt.Color(255, 153, 51));
        btnSalir.setText("Salir");
        panPago.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        btnCalcular.setBackground(new java.awt.Color(255, 153, 51));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        panPago.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 153, 51));
        btnCancelar.setText("Cancelar");
        panPago.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        btnRealizar1.setBackground(new java.awt.Color(255, 153, 51));
        btnRealizar1.setText("Realizar");
        btnRealizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizar1ActionPerformed(evt);
            }
        });
        panPago.add(btnRealizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(null);
        panPago.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        getContentPane().add(panPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnRealizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPagoDeNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPagoDeNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPagoDeNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPagoDeNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPagoDeNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRealizar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbEmpleadoPagar1;
    private javax.swing.JComboBox<String> cmbMesPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpanEncabezado1;
    private javax.swing.JLabel lblRegistrarCandidato1;
    private javax.swing.JPanel panPago;
    private javax.swing.JTextField txtMontoPagar;
    // End of variables declaration//GEN-END:variables
}
